language: python
python:
  - 3.5
install:
  - python -m pip install tox
script:
  - tox
env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=coverage
  - TOXENV=docs
  - TOXENV=pep8
sudo: false
